global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    file_sd_configs:
    - files:
      - "target_prometheus.json"

  - job_name: "node"
    file_sd_configs:
    - files:
      - "target_node.json"

  - job_name: "cus"
    file_sd_configs:
    - files:
      - "target_cus.json"

